version: '3.5'

services:
  rio.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - KEYSTONE_HOST=${KEYSTONE_HOST}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SITKA_EMAIL_REDIRECT=${SITKA_EMAIL_REDIRECT}
      - WEB_URL=${WEB_URL}
      - SECRET_PATH=${SECRET_PATH}
      - KEYSTONE_REDIRECT_URL=${KEYSTONE_REDIRECT_URL}
      - ALLOW_TRADING=${ALLOW_TRADING}
      - PlatformLongName=${PlatformLongName}
      - PlatformShortName=${PlatformShortName}
      - LeadOrganizationLongName=${LeadOrganizationLongName}
      - LeadOrganizationShortName=${LeadOrganizationShortName}
      - LeadOrganizationHomeUrl=${LeadOrganizationHomeUrl}
      - LeadOrganizationEmail=${LeadOrganizationEmail}
      - VerificationKeyChars=${VerificationKeyChars}
      - OpenETGoogleBucketBaseURL=${OpenETGoogleBucketBaseURL}
      - OpenETCheckRasterUpdatedDateBaseURL=${OpenETCheckRasterUpdatedDateBaseURL}
      - OpenETTriggerTimeSeriesBaseURL=${OpenETTriggerTimeSeriesBaseURL}
      - AllowOpenETSync=${AllowOpenETSync}
