version: '3.5'

services:
   geoserver:
      image: sitkacontainers.azurecr.io/rio/geoserver-2.15.1
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8777:8080"
      restart: on-failure
      env_file:
        - docker-env/geoserver.env
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3